#define BROADCAST_COMMAND 'B'
#define SET_ADDR_COMMAND 'S'
#define ANSWER_COMMAND 'A'
#define READ_TEMP_COMMAND 'D'
#define SLEEP_COMMAND 0x02
#define ERROR_COMMAND 0x11
#define STOP_BYTE 0xAA

#define ADC_MAX_VALUE 4095
